[workspace]
channels = ["conda-forge"]
name = "hands-on-pytorch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pytorch = ">=2.13.0,<3"
torchvision = ">=0.28.0,<0.29"
